name: Run Gradle on PRs
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload Pages
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: teavm/build/dist/webapp

  pages:
    needs: [gradle]
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v2
